# Generated by Django 3.1.7 on 2021-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_url',
            field=models.URLField(blank=True, help_text='Optional. If you provide a link here the map image will become a link'),
        ),
    ]
