# Generated by Django 3.1.7 on 2021-04-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_hourssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourssettings',
            old_name='contact',
            new_name='hours',
        ),
    ]
