# Generated by Django 3.1.7 on 2021-04-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('site_settings', '0004_auto_20210414_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCTASettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('button_text', models.CharField(default='Contact Us', max_length=25)),
                ('button_external_page', models.URLField(blank=True, help_text='If an internal page is selected, it will be used before the external page.')),
                ('button_internal_page', models.ForeignKey(blank=True, help_text='If an internal page is selected, it will be used before the external page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
