# Generated by Django 3.1.7 on 2021-04-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_footerctasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Enter your Facebook URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Enter your Instagram URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Enter your Twitter URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Enter your YouTube URL'),
        ),
    ]
